############################################################################
# apps/examples/mimonet/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_MIMONET_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_MIMONET_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_MIMONET_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_MIMONET)

MAINSRC = mimonet_main.c

include $(APPDIR)/Application.mk