/****************************************************************************
 * apps/examples/lvgldemo/ui_main.c
 *
 * Sign-language recognition main screen: light card layout.
 *   Left       : camera preview card (canvas written by camera module)
 *   Right top  : recognition result card
 *   Right below: speaker button card (plays a prompt on click)
 *
 * Ported from the ESP-IDF version of ui_main.c; only the pure LVGL
 * logic is kept.
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <string.h>

#include "ui_main.h"
#include "lvgl/lvgl.h"
#include "logo_data.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Light theme colors */

#define C_BG           lv_color_hex(0xf2f4f8)
#define C_CARD         lv_color_hex(0xffffff)
#define C_CARD_CAM     lv_color_hex(0xeef1f6)
#define C_PRIMARY      lv_color_hex(0x3b82f6)
#define C_PRIMARY_DIM  lv_color_hex(0x2563eb)
#define C_TEXT         lv_color_hex(0x1f2937)
#define C_TEXT_DIM     lv_color_hex(0x6b7280)
#define C_OK           lv_color_hex(0x10b981)
#define C_BORDER       lv_color_hex(0xe5e7eb)

/* Geometry */

#define UI_MARGIN   20
#define UI_GAP      20
#define CAM_W       600
#define CAM_H       560
#define SIDE_X      (UI_MARGIN + CAM_W + UI_GAP)
#define SIDE_W      (1024 - UI_MARGIN - SIDE_X)
#define RESULT_H    350
#define SPEAKER_Y   (UI_MARGIN + RESULT_H + UI_GAP)
#define SPEAKER_H   (UI_MARGIN + CAM_H - SPEAKER_Y)

/* UI strings (Chinese, \u-escaped) */

#define STR_CAMERA        "\u6444\u50cf\u5934"
#define STR_STANDBY       " \u5f85\u673a"
#define STR_CAM_AREA      "\u6444\u50cf\u5934\u753b\u9762\u533a\u57df"
#define STR_CAM_TIP       " \u8bf7\u5bf9\u51c6\u955c\u5934\uff0c" \
                          "\u4fdd\u6301\u624b\u90e8\u6e05\u6670"
#define STR_RESULT        "\u8bc6\u522b\u7ed3\u679c"
#define STR_CONF_FMT      "\u7f6e\u4fe1\u5ea6 %d%%"
#define STR_MUTED         "\u5df2\u9759\u97f3 \u00b7 " \
                          "\u518d\u6b21\u70b9\u51fb\u6062\u590d\u64ad\u62a5"
#define STR_BROADCAST     "\u5df2\u64ad\u62a5\u8bc6\u522b\u7ed3\u679c"
#define STR_SPEAKER       "\u8bed\u97f3\u64ad\u62a5"
#define STR_CLICK_PLAY    "\u70b9\u51fb\u64ad\u62a5\u8bc6\u522b\u7ed3\u679c"

/****************************************************************************
 * Private Data
 ****************************************************************************/

/* Chinese fonts + FontAwesome icons (generated by lv_font_conv,
 * with fallback)
 */

LV_FONT_DECLARE(zh_font_16);
LV_FONT_DECLARE(zh_font_40);

/* Speaker beep entry point (implemented by the audio module; silent
 * when not implemented)
 */

extern void board_audio_beep(void);

/* Camera preview canvas (the camera module writes frames into it) */

static lv_obj_t *s_cam_canvas = NULL;
static lv_obj_t *s_cam_status = NULL;

/* Common sign-language vocabulary (rotated as recognition demo) */

static const char *const g_vocab[] =
{
  "\u4f60\u597d",   "\u8c22\u8c22",   "\u5bf9\u4e0d\u8d77",
  "\u518d\u89c1",   "\u8f9b\u82e6\u4e86",
  "\u8bf7\u95ee",   "\u8bf7\u7a0d\u7b49",
  "\u53ef\u4ee5",   "\u597d\u7684",   "\u6211\u7231\u4f60",
};

#define VOCAB_NUM (sizeof(g_vocab) / sizeof(g_vocab[0]))

static lv_obj_t *s_word_label = NULL;
static lv_obj_t *s_conf_label = NULL;
static lv_obj_t *s_speaker_label = NULL;
static uint8_t s_vocab_idx = 0;

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/* Shared card style */

static void style_card(lv_obj_t *obj)
{
  lv_obj_remove_style_all(obj);
  lv_obj_set_style_bg_color(obj, C_CARD, 0);
  lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(obj, 18, 0);
  lv_obj_set_style_shadow_width(obj, 14, 0);
  lv_obj_set_style_shadow_color(obj, lv_color_hex(0x94a3b8), 0);
  lv_obj_set_style_shadow_opa(obj, LV_OPA_30, 0);
  lv_obj_set_style_border_width(obj, 1, 0);
  lv_obj_set_style_border_color(obj, C_BORDER, 0);
}

static void card_title(lv_obj_t *parent, const char *text, int y)
{
  lv_obj_t *bar = lv_obj_create(parent);
  lv_obj_remove_style_all(bar);
  lv_obj_set_style_bg_color(bar, C_PRIMARY, 0);
  lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(bar, 2, 0);
  lv_obj_set_size(bar, 5, 22);
  lv_obj_set_pos(bar, 20, y + 2);

  lv_obj_t *lbl = lv_label_create(parent);
  lv_obj_set_style_text_color(lbl, C_TEXT, 0);
  lv_obj_set_style_text_font(lbl, &zh_font_16, 0);
  lv_label_set_text(lbl, text);
  lv_obj_set_pos(lbl, 34, y);
}

/* Camera preview card */

static void create_camera_card(lv_obj_t *scr)
{
  lv_obj_t *card = lv_obj_create(scr);
  style_card(card);
  lv_obj_set_pos(card, UI_MARGIN, UI_MARGIN);
  lv_obj_set_size(card, CAM_W, CAM_H);

  card_title(card, STR_CAMERA, 18);

  lv_obj_t *status = lv_label_create(card);
  lv_obj_set_style_text_color(status, C_OK, 0);
  lv_obj_set_style_text_font(status, &zh_font_16, 0);
  lv_label_set_text(status, LV_SYMBOL_BULLET STR_STANDBY);
  lv_obj_align(status, LV_ALIGN_TOP_RIGHT, -20, 18);
  s_cam_status = status;

  /* Display area */

  lv_obj_t *disp = lv_obj_create(card);
  lv_obj_remove_style_all(disp);
  lv_obj_set_style_bg_color(disp, C_CARD_CAM, 0);
  lv_obj_set_style_bg_opa(disp, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(disp, 14, 0);
  lv_obj_set_pos(disp, 20, 56);
  lv_obj_set_size(disp, CAM_W - 40, CAM_H - 56 - 86);

  /* Camera preview canvas (the camera module writes RGB565 frames) */

  s_cam_canvas = lv_canvas_create(disp);
  lv_obj_remove_style_all(s_cam_canvas);
  lv_obj_set_size(s_cam_canvas, CAM_W - 40, CAM_H - 56 - 86);
  lv_obj_center(s_cam_canvas);

  /* Placeholder hint when no frame is available */

  lv_obj_t *cam_tip = lv_label_create(disp);
  lv_obj_set_style_text_color(cam_tip, C_TEXT_DIM, 0);
  lv_obj_set_style_text_font(cam_tip, &zh_font_16, 0);
  lv_label_set_text(cam_tip, STR_CAM_AREA);
  lv_obj_align(cam_tip, LV_ALIGN_BOTTOM_MID, 0, -24);

  /* Bottom hint bar */

  lv_obj_t *bar = lv_obj_create(card);
  lv_obj_remove_style_all(bar);
  lv_obj_set_style_bg_color(bar, C_CARD_CAM, 0);
  lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(bar, 12, 0);
  lv_obj_set_pos(bar, 20, CAM_H - 66);
  lv_obj_set_size(bar, CAM_W - 40, 46);

  lv_obj_t *tip = lv_label_create(bar);
  lv_obj_set_style_text_color(tip, C_TEXT_DIM, 0);
  lv_obj_set_style_text_font(tip, &zh_font_16, 0);
  lv_label_set_text(tip, LV_SYMBOL_WARNING STR_CAM_TIP);
  lv_obj_center(tip);
}

/* Recognition result card */

static void create_result_card(lv_obj_t *scr)
{
  lv_obj_t *card = lv_obj_create(scr);
  style_card(card);
  lv_obj_set_pos(card, SIDE_X, UI_MARGIN);
  lv_obj_set_size(card, SIDE_W, RESULT_H);

  card_title(card, STR_RESULT, 18);

  lv_obj_t *word = lv_label_create(card);
  lv_obj_set_style_text_color(word, C_TEXT, 0);
  lv_obj_set_style_text_font(word, &zh_font_40, 0);
  lv_label_set_text(word, g_vocab[0]);
  lv_obj_align(word, LV_ALIGN_CENTER, 0, -24);
  s_word_label = word;

  /* Confidence progress bar */

  lv_obj_t *bar = lv_bar_create(card);
  lv_obj_remove_style_all(bar);
  lv_obj_set_size(bar, SIDE_W - 60, 10);
  lv_obj_set_style_bg_color(bar, lv_color_hex(0xe5e7eb), 0);
  lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(bar, 5, 0);
  lv_obj_align(bar, LV_ALIGN_BOTTOM_MID, 0, -58);
  lv_obj_set_style_bg_color(bar, C_PRIMARY, LV_PART_INDICATOR);
  lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, LV_PART_INDICATOR);
  lv_obj_set_style_radius(bar, 5, LV_PART_INDICATOR);
  lv_bar_set_range(bar, 0, 100);
  lv_bar_set_value(bar, 96, LV_ANIM_ON);

  lv_obj_t *conf = lv_label_create(card);
  lv_obj_set_style_text_color(conf, C_TEXT_DIM, 0);
  lv_obj_set_style_text_font(conf, &zh_font_16, 0);
  lv_label_set_text(conf, "\u7f6e\u4fe1\u5ea6 96%");
  lv_obj_align(conf, LV_ALIGN_BOTTOM_MID, 0, -32);
  s_conf_label = conf;
}

/* Speaker button click callback: play the prompt and show feedback */

static void speaker_click_cb(lv_event_t *e)
{
  lv_obj_t *btn = lv_event_get_target(e);
  lv_obj_t *icon = lv_obj_get_child(btn, 0);

  /* Play the prompt (real speaker output) */

  board_audio_beep();

  if (strcmp(lv_label_get_text(icon), LV_SYMBOL_VOLUME_MAX) == 0)
    {
      lv_label_set_text(icon, LV_SYMBOL_MUTE);
      lv_obj_set_style_bg_color(btn, C_TEXT_DIM, 0);
      lv_obj_set_style_bg_grad_color(btn, lv_color_hex(0x9aa3b0), 0);
      lv_label_set_text(s_speaker_label, STR_MUTED);
    }
  else
    {
      lv_label_set_text(icon, LV_SYMBOL_VOLUME_MAX);
      lv_obj_set_style_bg_color(btn, C_PRIMARY, 0);
      lv_obj_set_style_bg_grad_color(btn, C_PRIMARY_DIM, 0);
      lv_label_set_text(s_speaker_label, STR_BROADCAST);
    }
}

/* Vocabulary rotation timer: switch the demo word every 2 seconds */

static void vocab_timer_cb(lv_timer_t *timer)
{
  s_vocab_idx = (s_vocab_idx + 1) % VOCAB_NUM;
  if (s_word_label != NULL)
    {
      lv_label_set_text(s_word_label, g_vocab[s_vocab_idx]);
    }

  if (s_conf_label != NULL)
    {
      char buf[32];
      snprintf(buf, sizeof(buf), STR_CONF_FMT,
               88 + (s_vocab_idx * 3) % 10);
      lv_label_set_text(s_conf_label, buf);
    }
}

/* Speaker button card */

static void create_speaker_card(lv_obj_t *scr)
{
  lv_obj_t *card = lv_obj_create(scr);
  style_card(card);
  lv_obj_set_pos(card, SIDE_X, SPEAKER_Y);
  lv_obj_set_size(card, SIDE_W, SPEAKER_H);

  card_title(card, STR_SPEAKER, 18);

  /* Round speaker button (with click feedback) */

  lv_obj_t *btn = lv_obj_create(card);
  lv_obj_remove_style_all(btn);
  lv_obj_set_size(btn, 76, 76);
  lv_obj_set_style_bg_color(btn, C_PRIMARY, 0);
  lv_obj_set_style_bg_grad_color(btn, C_PRIMARY_DIM, 0);
  lv_obj_set_style_bg_grad_dir(btn, LV_GRAD_DIR_VER, 0);
  lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(btn, 38, 0);
  lv_obj_set_style_shadow_width(btn, 16, 0);
  lv_obj_set_style_shadow_color(btn, C_PRIMARY, 0);
  lv_obj_set_style_shadow_opa(btn, LV_OPA_40, 0);
  lv_obj_set_style_bg_color(btn, lv_color_hex(0x1e40af),
                            LV_STATE_PRESSED);
  lv_obj_set_style_transform_scale(btn, 230, LV_STATE_PRESSED);
  lv_obj_set_style_shadow_width(btn, 6, LV_STATE_PRESSED);
  lv_obj_add_flag(btn, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_align(btn, LV_ALIGN_CENTER, 0, -8);

  lv_obj_t *icon = lv_label_create(btn);
  lv_obj_set_style_text_color(icon, lv_color_white(), 0);
  lv_obj_set_style_text_font(icon, &zh_font_16, 0);
  lv_label_set_text(icon, LV_SYMBOL_VOLUME_MAX);
  lv_obj_center(icon);

  lv_obj_t *label = lv_label_create(card);
  lv_obj_set_style_text_color(label, C_TEXT_DIM, 0);
  lv_obj_set_style_text_font(label, &zh_font_16, 0);
  lv_label_set_text(label, STR_CLICK_PLAY);
  lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -14);
  s_speaker_label = label;

  lv_obj_add_event_cb(btn, speaker_click_cb, LV_EVENT_CLICKED, NULL);
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: ui_main_get_camera_canvas
 *
 * Description:
 *   Return the camera preview canvas for the camera module to render
 *   frames into.
 *
 * Returned Value:
 *   The canvas object, or NULL before ui_main_create() runs.
 *
 ****************************************************************************/

lv_obj_t *ui_main_get_camera_canvas(void)
{
  return s_cam_canvas;
}

/****************************************************************************
 * Name: ui_main_get_current_word
 *
 * Description:
 *   Return the currently displayed vocabulary word.
 *
 * Returned Value:
 *   A pointer to the current NUL-terminated word string.
 *
 ****************************************************************************/

const char *ui_main_get_current_word(void)
{
  return g_vocab[s_vocab_idx % VOCAB_NUM];
}

/****************************************************************************
 * Name: ui_main_set_camera_status
 *
 * Description:
 *   Update the camera card status label text.
 *
 * Input Parameters:
 *   text - New status text, or NULL to keep the current text.
 *
 ****************************************************************************/

void ui_main_set_camera_status(const char *text)
{
  if (s_cam_status != NULL && text != NULL)
    {
      lv_label_set_text(s_cam_status, text);
    }
}

/****************************************************************************
 * Name: ui_main_create
 *
 * Description:
 *   Build the main screen: camera preview card, recognition result
 *   card and speaker card, plus the vocabulary rotation timer.
 *
 * Input Parameters:
 *   scr - The LVGL screen object to build the UI onto.
 *
 ****************************************************************************/

void ui_main_create(lv_obj_t *scr)
{
  /* Clear whatever remains of the boot screen */

  lv_obj_clean(scr);

  lv_obj_set_style_bg_color(scr, C_BG, 0);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

  create_camera_card(scr);
  create_result_card(scr);
  create_speaker_card(scr);

  /* Vocabulary rotation demo (switch every 2 seconds) */

  lv_timer_create(vocab_timer_cb, 2000, NULL);
}
